/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    requires: [
        'net_utils.controller.NetConfig',
        'net_utils.controller.NicInfo',
        'net_utils.controller.NetSpeed'
    ],

    models: [
        'testunit'
    ],
    stores: [
        'testunit'
    ],
    views: [
        'MainView',
        'changepassword'
    ],
    autoCreateViewport: true,
    name: 'app_unittest',
    controllers: [
        'LoadTest'
    ],
    defaultlang: 'zh_cn'
});
