Ext.ns('App.locale');
App.locale.text = {
	'Access': '访问权限',
	'Add New ...': '添加...',
	'Add New': '添加',
	'Blockdev': '块设备',
	'Broadcast': '广播地址',
	'Busid': '总线ID',
	'Capacity': '容量',
	'Clientip': '客户端IP',
	'Count': '计数',
	'Current License': '当前license',
	'Current Setting': '当前设定',
	'Date': '日期',
	'Delete': '删除',
	'Description': '描述',
	'Destinationip': '目标IP',
	'Detail log inforamtion': '详细日志信息',
	'Dev': '设备',
	'Disks': '磁盘管理',
	'Download All': '下载日志',
	'Excludesource': '',
	'Facility': '对象',
	'Fixed': '固定磁盘',
	'GW & DNS': '网关和DNS',
	'Global CHAP Setting': '全局CHAP设定',
	'Global Setting': '全局设定',
	'HBA setting': '磁盘通道设定',
	'Host Setting': '主机设定',
	'Host': '主机',
	'HostName': '主机名',
	'IP Address Configuration': 'IP地址配置',
	'IP address of current visited server %ipaddress% will be deleted, you need restrart the web application, are you sure?': '正在访问的服务器IP %ipaddress% 将被删除，需要使用新的地址重新进入web应用，您确定么？',
	'Includeip': '物理IP',
	'Initiator': '启动器',
	'Initiatorpass': '启动器密码',
	'Initiatoruser': '启动器用户',
	'Ipaddress': 'IP地址',
	'Ipv6address': 'IPV6地址',
	'License': '授权',
	'LunMap': 'LUN映射',
	'Maintain': '系统维护',
	'Mapping CHAP Setting': '映射相关的CHAP设定',
	'Message': '日志',
	'NIC & IP Address': '网卡IP设定',
	'NIC Setting': '网卡信息',
	'Netmask': '子网掩码',
	'Network Bandwidth Monitor': '网络流量监视器',
	'Network': '网络设定',
	'New Mapping': '新的映射',
	'Physicdevice': '物理网卡',
	'Product': '产品型号',
	'Readspeed': '读取速度',
	'Refresh': '刷新',
	'Reload': '重载',
	'Rescan ...': '重新扫描...',
	'Revision': '版本',
	'Rxbytes': '发送字节数',
	'Save': '保存',
	'Scsi_device': 'SCSI设备号',
	'Setting': '设定',
	'Sourceip': '源IP',
	'SysInfo': '系统信息',
	'System Log': '系统日志',
	'System information': '系统信息',
	'Targetid': '目标ID',
	'Targetip': '目标IP',
	'Targetname': '目标IQN',
	'Targetpass': '目标密码',
	'Targetuser': '目标用户',
	'Test ...': '测试 ...',
	'Time': '时间',
	'Txbytes': '发送字节数',
	'Type': '类型',
	'Update': '更新',
	'Upload': '上传',
	'Vendor': '厂家',
	'Virt Portal': '虚拟IP',
	'Virtual Portal': '虚拟IP',
	'Writespeed': '写入速度',
	'__x': '',
	'delete': '删除',
	'disconnect': '断开连接',
	'iSCSI Connection': 'iSCSI连接信息',
	'iSCSI': 'iSCSI设定',
	'iSCSI连接': '',
	'refresh': '刷新',
	'系统信息': '',
	'网卡设定': '',
};
