/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    requires: [
        'ui_common.controller.DataIndicator',
        'ui_common.controller.EventMessager',
        'sys_misc.controller.PciInfo',
        'sys_misc.controller.SysSetting',
        'net_utils.controller.NetConfig',
        'net_utils.controller.NicInfo',
        'target_iscsi.controller.iSCSIConn',
        'target_iscsi.controller.LunMap',
        'target_iscsi.controller.VirtPortal',
        'storage_scsi.controller.ScsiDisks',
        'net_utils.controller.NetSpeed'
    ],

    views: [
        'MainView',
        'BigIconBtn',
        'SystemInfo',
        'NetworkSetting',
        'iSCSISetting',
        'DiskSetting',
        'SystemMaintain',
        'changepassword'
    ],
    autoCreateViewport: true,
    name: 'app_iwm',
    controllers: [
        'MainMenu'
    ],
    defaultlang: 'zh_cn',

    launch: function() {
        this.UISetting = {
            sysinfo:['sys_misc.view.PciInfo', 'net_utils.view.NicInfo', 'target_iscsi.view.iSCSIConn', 'net_utils.view.LinkSpeedBar'],
            network:['net_utils.view.NetConfig'],
            disks:['storage_scsi.view.DiskMgmt'],
            iscsi:['target_iscsi.view.LunMap', 'target_iscsi.view.VirtPortal'],
            maintain:['sys_misc.view.SysMaintain'],
            logout:[]
        };
        var btn = Ext.getCmp('sysinfo');
        btn.fireEvent('click', btn);
    }

});
