/*
 * File: app/controller/Login.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Login', {
    extend: 'Ext.app.Controller',

    views: [
        'Login'
    ],

    onLoginok: function(host) {
        var app = this,
            lwin = Ext.getCmp('loginwindow');

        lwin.hide();
        lwin.logouted = false;
        if (!app.mainview){
            app.mainview = Ext.widget('mainview', {serverip: host});
        }
    },

    onLoginfail: function(host) {
        var lwin = Ext.getCmp('loginwindow');

        if (!lwin){
            lwin = this.getView('Login').create();
        }
        if (!lwin.isVisible()) lwin.show();
    },

    onLoginloaded: function(store, form) {
        var m = store.getAt(0);
        if (!m) return;
        //todo: get saved user from form.state?
        form.getForm().loadRecord(m);
        this.loginstore = store;
    },

    onLogout: function() {
        var store = this.loginstore,
            params = Ext.apply({_logout:true}, store.reloadParams);
        store.load({params:params});
        var lwin = Ext.getCmp('loginwindow');
        lwin.logouted = true;
        lwin.show();

    },

    init: function() {

        this.application.on({
            loginok: {
                fn: this.onLoginok
            },
            loginfail: {
                fn: this.onLoginfail
            },
            loginloaded: {
                fn: this.onLoginloaded
            },
            logout: {
                fn: this.onLogout
            }
        });

    }

});
