/*
 * File: app/view/DiskMgmt.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('storage_scsi.view.DiskMgmt', {
    extend: 'Ext.form.Panel',
    alias: 'widget.diskmgmt',

    cls: 'shadowpanel',
    layout: {
        type: 'border'
    },
    bodyPadding: 10,
    title: 'Disk Management$',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    hideCollapseTool: false,
                    overlapHeader: false,
                    preventHeader: false,
                    title: 'Current Setting$',
                    titleCollapse: false,
                    databind: {
                        autoload: true,
                        model: 'storage_scsi.model.scsidisk'
                    },
                    region: 'center',
                    split: true,
                    viewConfig: {

                    },
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'delete',
                                    text: 'Delete'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'refresh',
                                    text: 'Refresh'
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'blockdev',
                            text: 'Blockdev'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'capacity',
                            text: 'Capacity'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'vendor',
                            text: 'Vendor'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'product',
                            text: 'Product'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'revision',
                            text: 'Revision'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'fixed',
                            text: 'Fixed'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'host',
                            text: 'Host'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'scsi_device',
                            text: 'Scsi_device'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    minWidth: 292,
                    width: 292,
                    autoScroll: true,
                    region: 'west',
                    split: true,
                    items: [
                        {
                            xtype: 'form',
                            border: 0,
                            bodyCls: 'x-border-layout-ct',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'HBA setting',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            itemId: 'scsihost',
                                            name: 'host',
                                            fieldLabel: 'Disk Channel',
                                            displayField: 'shortname',
                                            queryMode: 'local',
                                            valueField: 'dev',
                                            databind: {
                                                autoload: true,
                                                model: 'storage_scsi.model.scsihost'
                                            },
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'rescan',
                                            text: 'Rescan ...',
                                            listeners: {
                                                click: {
                                                    fn: me.onRescanClick,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onRescanClick: function(button, e, options) {
        var me= button,
            c = me.up().down('#scsihost'),
            s = c.store,
            v = c.getValue();
        if (!c.store) return;
        var m = s.findRecord('dev', v);
        if (!m) return;
        m.setDirty();
        s.sync();

    }

});