/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'netconfig',
        'IscsiConn',
        'SysInfo',
        'targetlist',
        'LunMap',
        'access',
        'virtportal',
        'DiskList',
        'HbaList',
        'SysLog',
        'etherspeed',
        'glunmap',
        'dnsgw',
        'gvirtportal',
        'niclist'
    ],
    stores: [
        'networkinfo',
        'netconfig',
        'physicinfo',
        'iscsiconn',
        'sysinfo',
        'targetlist',
        'LunMap',
        'Access',
        'VirtPortal',
        'DiskList',
        'HbaList',
        'SysLog',
        'LinkSpeed'
    ],
    views: [
        'MyViewport',
        'BigIconBtn',
        'SystemInfo',
        'NetworkSetting',
        'iSCSISetting',
        'DiskSetting',
        'SystemMaintain',
        'NetMaskField',
        'TargetListField',
        'NetConfig',
        'VirtPortal',
        'DiskMgmt',
        'SysMaintain',
        'LinkSpeed',
        'LinkSpeedBar',
        'LunMap'
    ],
    autoCreateViewport: true,
    name: 'MyApp',
    controllers: [
        'DBinder',
        'MainMenu',
        'MaskDBClick',
        'DataIndiacator',
        'EventManager'
    ],

    launch: function() {
        alert('aa');
    }

});
