/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app_unittest.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    cls: 'viewbg',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    cls: 'whitebg',
                    height: 80,
                    id: 'menuarea',
                    padding: '0px 50px ',
                    layout: {
                        align: 'stretch',
                        padding: '0px 50px ',
                        type: 'vbox'
                    },
                    floatable: false,
                    region: 'north',
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            padding: 5,
                            layout: {
                                type: 'table'
                            },
                            fieldLabel: 'Label',
                            hideLabel: true,
                            flex: 1,
                            margins: 5,
                            items: [
                                {
                                    xtype: 'combobox',
                                    itemId: 'testunitselector',
                                    width: 337,
                                    fieldLabel: 'Load Unit',
                                    queryMode: 'local',
                                    valueField: 'text',
                                    databind: {
                                        autoload: true,
                                        model: 'testunit',
                                        mid: 'test.testunit'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'serverip',
                                    fieldLabel: 'serverip',
                                    labelAlign: 'right'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'unitconfig',
                                    fieldLabel: 'other config',
                                    labelAlign: 'right'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            padding: 5,
                            layout: {
                                type: 'table'
                            },
                            fieldLabel: 'Label',
                            hideLabel: true,
                            flex: 1,
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    itemId: 'multiinstance',
                                    name: 'multiinstance',
                                    fieldLabel: 'Multi Instance',
                                    boxLabel: 'Enable'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'loadoneunit',
                                    text: 'Load This Unit'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'loadtest',
                                    text: 'Load All Units'
                                },
                                {
                                    xtype: 'button',
                                    id: 'show_unlocalized',
                                    text: 'show unlocalized'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    floating: false,
                    id: 'content',
                    padding: '20px 20px 20px 100px',
                    activeItem: 0,
                    layout: {
                        type: 'card'
                    },
                    floatable: false,
                    region: 'center',
                    items: [
                        {
                            xtype: 'tabpanel',
                            id: 'testpanel',
                            closable: false,
                            activeTab: 1,
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    title: 'My Grid Panel',
                                    databind: {
                                        loadparams: {
                                            callremote: true
                                        },
                                        progress: {
                                            type: 'bar'
                                        },
                                        model: 'app_unittest.model.jobtest'
                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'String'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Number'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'date',
                                            text: 'Date'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'bool',
                                            text: 'Boolean'
                                        }
                                    ],
                                    viewConfig: {

                                    },
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    itemId: 'refresh',
                                                    text: 'reload'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});