/*
 * File: app/view/PciInfo.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sys_misc.view.PciInfo', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.pciinfo',

    itemId: 'sysinfo',
    title: 'System Information$',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            databind: {
                autoload: true,
                model: 'sys_misc.model.pciinfo'
            },
            viewConfig: {

            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'refresh',
                            text: 'refresh'
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 78,
                    dataIndex: 'busid',
                    text: 'Busid'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return '<span class="x-column-icon x-hardware-'+value.replace(/ +/g, '_').toLowerCase()+'"> </span><span class=x-column-icon-text>'+value+'</span>';
                    },
                    width: 177,
                    dataIndex: 'type',
                    text: 'Type',
                    databind: {
                        autoload: true,
                        model: 'pciinfo'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    width: 139,
                    dataIndex: 'vendor',
                    text: 'Vendor'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'description',
                    flex: 1,
                    text: 'Description'
                }
            ]
        });

        me.callParent(arguments);
    }

});