/*
 * File: app/store/nicinfo.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.nicinfo', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.NicInfo'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'nicinfo',
            model: 'MyApp.model.NicInfo',
            data: [
                {
                    dev: 'eth0',
                    physicdevice: 'eth0',
                    ipaddress: '192.168.10.1'
                },
                {
                    dev: 'eth1',
                    physicdevice: 'eth1',
                    ipaddress: '192.168.20.1'
                }
            ],
            groupField: 'physicdevice',
            proxy: {
                type: 'jsonp',
                extraParams: [
                    'action'
                ],
                reader: {
                    type: 'json'
                },
                writer: {
                    type: 'json',
                    writeAllFields: false,
                    allowSingle: false,
                    root: 'data'
                }
            }
        }, cfg)]);
    }
});