/*
 * File: app/store/SysLog.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.SysLog', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.SysLog'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyJsonPStore10',
            model: 'MyApp.model.SysLog',
            data: [
                {
                    date: '2009-12-24 19:12:35',
                    facility: 'kernel',
                    message: 'abadfasd asdfadsf<br /> adsfadsf adsfa dsfasdfafd asdfadsf adsfadf '
                }
            ]
        }, cfg)]);
    }
});