/*
 * File: app/store/VirtPortal.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.VirtPortal', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.VirtPortal'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'virtportal',
            model: 'MyApp.model.VirtPortal',
            data: [
                {
                    targetid: -1,
                    targetname: 'default',
                    includeip: '10.10.1.201'
                },
                {
                    targetid: -1,
                    targetname: 'default',
                    excludesource: '10.10.1.1'
                },
                {
                    targetid: 0,
                    targetname: 'iqn:0',
                    includeip: '10.10.1.222'
                }
            ],
            groupField: 'targetname',
            sorters: {
                direction: 'DESC',
                property: 'includeip'
            }
        }, cfg)]);
    }
});