/*
 * File: app/controller/EventManager.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('lib_core.controller.EventManager', {
    extend: 'Ext.app.Controller',
    alias: 'controller.eventmanager',

    views: [
        'Messager'
    ],

    refs: [
        {
            ref: 'messager',
            selector: '#messager'
        }
    ],

    onDatadone: function(info) {
        var m = this.getMessager();

        if (!m){
            this.getView('Messager').create();
            m = this.getMessager();
        }
        m.showPopup('datadone', info);
    },

    init: function() {

        this.application.on({
            datadone: {
                fn: this.onDatadone,
                scope: this
            }
        });

    }

});
