/*
 * File: app/view/SysMaintain.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SysMaintain', {
    extend: 'Ext.form.Panel',
    alias: 'widget.sysmaintain',

    layout: {
        type: 'border'
    },
    bodyPadding: 10,
    title: 'System Maintain$',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    hideCollapseTool: false,
                    overlapHeader: false,
                    preventHeader: false,
                    title: 'System Log$',
                    titleCollapse: false,
                    store: 'SysLog',
                    region: 'center',
                    split: true,
                    viewConfig: {

                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'download',
                                    text: 'Download',
                                    listeners: {
                                        click: {
                                            fn: me.onDownloadClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: 'Clear All'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Clear This'
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Choose Log',
                                    hideLabel: false,
                                    labelWidth: 80,
                                    queryMode: 'local'
                                },
                                {
                                    xtype: 'pagingtoolbar',
                                    width: 360,
                                    displayInfo: true,
                                    flex: 1
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            minWidth: 120,
                            dataIndex: 'date',
                            text: 'Date'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'facility',
                            text: 'Facility'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'message',
                            flex: 1,
                            text: 'Message'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    minWidth: 292,
                    width: 292,
                    autoScroll: true,
                    region: 'west',
                    split: true,
                    items: [
                        {
                            xtype: 'form',
                            border: 0,
                            bodyCls: 'x-border-layout-ct',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Host Setting$',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'HostName$',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'Date$',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'timefield',
                                            fieldLabel: 'Time$',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'update',
                                            text: 'Update$'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'refresh',
                                            text: 'Refresh'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            border: 0,
                            bodyCls: 'x-border-layout-ct',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'License',
                                    items: [
                                        {
                                            xtype: 'filefield',
                                            fieldLabel: 'New license',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'add',
                                            text: 'Update$'
                                        },
                                        {
                                            xtype: 'fieldset',
                                            collapsed: true,
                                            collapsible: true,
                                            title: 'Current License',
                                            items: [
                                                {
                                                    xtype: 'textareafield',
                                                    fieldLabel: 'Old license',
                                                    hideLabel: true,
                                                    labelAlign: 'top',
                                                    anchor: '100%'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'update',
                                                    text: 'Test ...'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onDownloadClick: function(button, e, options) {

    }

});