/*
 * File: app/view/SysMaintain.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SysMaintain', {
    extend: 'Ext.form.Panel',
    alias: 'widget.sysmaintain',

    layout: {
        type: 'border'
    },
    bodyPadding: 10,
    title: 'System Maintain$',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    hideCollapseTool: false,
                    overlapHeader: false,
                    preventHeader: false,
                    title: 'System Log$',
                    titleCollapse: false,
                    store: 'SysLog',
                    databind: {
                        autoload: true,
                        model: 'syslog'
                    },
                    region: 'center',
                    split: true,
                    viewConfig: {

                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'download',
                                    text: 'Download',
                                    listeners: {
                                        click: {
                                            fn: me.onDownloadClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'deleteall',
                                    text: 'Clear All'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'deletethis',
                                    text: 'Clear This'
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Choose Log',
                                    hideLabel: false,
                                    labelWidth: 80,
                                    displayField: 'logname',
                                    queryMode: 'local',
                                    valueField: 'logname',
                                    databind: {
                                        autoload: true,
                                        model: 'logfiles'
                                    },
                                    listeners: {
                                        change: {
                                            fn: me.onComboboxChange,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 46,
                            dataIndex: 'line',
                            text: 'Line'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'date',
                            text: 'Date'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 76,
                            dataIndex: 'facility',
                            text: 'Facility'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'message',
                            flex: 1,
                            text: 'Message'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    minWidth: 292,
                    width: 292,
                    autoScroll: true,
                    region: 'west',
                    split: true,
                    items: [
                        {
                            xtype: 'form',
                            border: 0,
                            bodyCls: 'x-border-layout-ct',
                            databind: {
                                autoload: true,
                                model: 'hostsetting'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Host Setting$',
                                    databind: {
                                        autoload: true,
                                        model: 'hostsetting'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            name: 'hostname',
                                            fieldLabel: 'HostName$',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'datefield',
                                            name: 'date',
                                            fieldLabel: 'Date$',
                                            format: 'Y-m-d',
                                            submitFormat: 'Y-m-d',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'textfield',
                                            name: 'time',
                                            fieldLabel: 'Time$',
                                            allowBlank: false,
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'combobox',
                                            name: 'timezone',
                                            value: 'Asia/Shanghai',
                                            fieldLabel: 'TimeZone',
                                            displayField: 'shortname',
                                            queryMode: 'local',
                                            valueField: 'zone',
                                            databind: {
                                                autoload: true,
                                                model: 'timezone',
                                                loadonce: true
                                            },
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'update',
                                            text: 'Update$',
                                            formBind: true
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'refresh',
                                            text: 'Refresh',
                                            formBind: true
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            border: 0,
                            bodyCls: 'x-border-layout-ct',
                            databind: {
                                autoload: true,
                                model: 'license'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'License',
                                    databind: {
                                        model: 'license',
                                        autoload: true
                                    },
                                    items: [
                                        {
                                            xtype: 'filefield',
                                            name: 'licensefile',
                                            fieldLabel: 'New license',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'add',
                                            text: 'Update$'
                                        },
                                        {
                                            xtype: 'fieldset',
                                            collapsed: true,
                                            collapsible: true,
                                            title: 'Current License',
                                            items: [
                                                {
                                                    xtype: 'textareafield',
                                                    name: 'licensedata',
                                                    fieldLabel: 'Old license',
                                                    hideLabel: true,
                                                    labelAlign: 'top',
                                                    anchor: '100%'
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'update',
                                                    text: 'Test ...',
                                                    forceupdate: true
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'refresh',
                                                    text: 'Reload'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onDownloadClick: function(button, e, options) {

    },

    onComboboxChange: function(field, newValue, oldValue, options) {
        var store = field.up('gridpanel').getStore();
        store.load({params:{_logname:newValue}});
    }

});