/*
 * File: app/store/ScsiHost.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('lib_core.store.ScsiHost', {
    extend: 'Ext.data.Store',
    requires: [
        'lib_core.model.scsihost'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyJsonPStore9',
            model: 'lib_core.model.scsihost',
            data: [
                {
                    hostid: 'host1',
                    hostdesc: 'lsi sas adapter'
                },
                {
                    hostid: 'host2',
                    hostdesc: 'iscsi initiator'
                }
            ]
        }, cfg)]);
    }
});