/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('net_utils.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',
    requires: [
        'net_utils.view.LinkSpeedBar',
        'net_utils.view.NetConfig',
        'net_utils.view.NicInfo'
    ],

    cls: 'viewbg',
    id: 'viewport',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    cls: 'whitebg',
                    height: 80,
                    id: 'menuarea',
                    padding: '0px 50px ',
                    floatable: false,
                    region: 'north',
                    items: [
                        {
                            xtype: 'button',
                            id: 'show_unlocalized',
                            text: 'show unlocalized'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    floating: false,
                    id: 'content',
                    padding: '20px 20px 20px 100px',
                    activeItem: 0,
                    layout: {
                        type: 'card'
                    },
                    floatable: false,
                    region: 'center',
                    items: [
                        {
                            xtype: 'tabpanel',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'linkspeedbar'
                                },
                                {
                                    xtype: 'netconfig'
                                },
                                {
                                    xtype: 'nicinfo'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});