/*
 * File: app/view/NetConfig.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('net_utils.view.NetConfig', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.netconfig',
    requires: [
        'net_utils.view.IpField',
        'net_utils.view.NetMaskField'
    ],

    cls: 'shadowpanel',
    minHeight: 300,
    layout: {
        type: 'border'
    },
    bodyPadding: 10,
    title: 'NIC Setting$',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    itemId: 'nicinfo',
                    hideCollapseTool: false,
                    overlapHeader: false,
                    preventHeader: false,
                    title: 'NIC & IP Address',
                    titleCollapse: false,
                    store: 'net_utils.store.netconfig',
                    databind: {
                        bindform: 'nic',
                        mid: 'netconfig',
                        autoload: 'true'
                    },
                    region: 'center',
                    split: true,
                    viewConfig: {

                    },
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    getConfirmation: function(button, value, records, store) {
                                        if (!records.length) return false;
                                        for(var i=0; i<records.length; i++){
                                            var r = records[i].getData();
                                            if (r.ipaddress == location.host) return {
                                                title: button.confirmtitle,
                                                msg: button.confirmation.replace('%ipaddress%', r.ipaddress)
                                            };
                                        }
                                        return false;
                                    },
                                    disabled: true,
                                    itemId: 'delete',
                                    text: 'Delete',
                                    confirmation: 'IP address of current visited server %ipaddress% will be deleted, you need restrart the web application, are you sure?$',
                                    confirmtitle: 'Warning'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'refresh',
                                    text: 'Refresh'
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'dev',
                            text: 'Dev'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'physicdevice',
                            text: 'Physicdevice'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ipaddress',
                            text: 'Ipaddress'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ipv6address',
                            text: 'Ipv6address'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'netmask',
                            text: 'Netmask'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'broadcast',
                            text: 'Broadcast'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    minWidth: 290,
                    width: 290,
                    autoScroll: true,
                    region: 'west',
                    split: true,
                    items: [
                        {
                            xtype: 'form',
                            border: 0,
                            itemId: 'global',
                            bodyCls: 'x-border-layout-ct',
                            databind: {
                                model: 'net_utils.model.dnsgw',
                                autoload: true,
                                reloadonactive: true
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    padding: 5,
                                    collapsed: true,
                                    collapsible: true,
                                    title: 'GW & DNS',
                                    items: [
                                        {
                                            xtype: 'ipfield',
                                            name: 'defgw1',
                                            fieldLabel: 'Default GW1'
                                        },
                                        {
                                            xtype: 'ipfield',
                                            name: 'defgw2',
                                            fieldLabel: 'Default GW2'
                                        },
                                        {
                                            xtype: 'ipfield',
                                            name: 'dns1',
                                            fieldLabel: 'DNS1'
                                        },
                                        {
                                            xtype: 'ipfield',
                                            name: 'dns2',
                                            fieldLabel: 'DNS2'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'update',
                                            text: 'Save'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'refresh',
                                            text: 'Refresh'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            border: 0,
                            itemId: 'nic',
                            bodyCls: 'x-border-layout-ct',
                            bindto: 'nicinfo',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    padding: 5,
                                    collapsed: false,
                                    collapsible: true,
                                    title: 'IP Address Configuration',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            name: 'dev',
                                            fieldLabel: 'Device Name',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'combobox',
                                            name: 'physicdevice',
                                            fieldLabel: 'NIC',
                                            displayField: 'shortname',
                                            valueField: 'physicdevice',
                                            databind: {
                                                autoload: true,
                                                model: 'net_utils.model.niclist'
                                            },
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'ipfield',
                                            name: 'ipaddress',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'netmaskfield',
                                            name: 'netmask',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'add',
                                            margin: 5,
                                            minWidth: 80,
                                            autoWidth: true,
                                            text: 'Add New',
                                            formBind: true
                                        },
                                        {
                                            xtype: 'button',
                                            itemId: 'update',
                                            text: 'Update'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});