/*
 * File: app/view/iSCSISetting.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('iwm.view.iSCSISetting', {
    extend: 'Ext.container.Container',
    alias: 'widget.iscsisetting',
    requires: [
        'iwm.view.LunMap',
        'iwm.view.VirtPortal'
    ],

    height: 600,
    width: 600,
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    cls: 'shadowpanel',
                    padding: 10,
                    activeTab: 0,
                    region: 'center',
                    items: [
                        {
                            xtype: 'lunmap',
                            bodyBorder: false
                        },
                        {
                            xtype: 'virtportal'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});